OBS_NOISE = 0.1

SENSOR_TRUE_CONFIDENCE = 0.9995
SENSOR_FALSE_CONFIDENCE = 0.9995

PICKED_UP_DETECTION_TRUE_PROB_MEAN = 0.8
PICKED_UP_DETECTION_TRUE_PROB_STD = 0.1
PICKED_UP_DETECTION_FALSE_PROB_MEAN = 0.2
PICKED_UP_DETECTION_FALSE_PROB_STD = 0.1

ADD_TO_BUFFER_PROB_THRESHOLD = 0.996
PROB_TRANSITION_THRESHOLD_UNIVERSAL = 0.996
PROB_TRANSITION_THRESHOLD_EXISTENTIAL = 0.996
